In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

After running the above cell, you'll be prompted to authenticate your Google account. Once authenticated, your Google Drive will be mounted at `/content/drive`. You can then access your files, for example, a CSV file named `my_data.csv` located in the root of your Drive, like this:

In [ ]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Credit_test/credit_test.csv')

In [ ]:
import pandas as pd

# Example: Reading a CSV file from your Google Drive
# Make sure to replace 'my_data.csv' with the actual path to your file in Drive
# For example, if your file is in 'My Drive/Colab Notebooks/data.csv', the path would be '/content/drive/My Drive/Colab Notebooks/data.csv'
try:
    df = pd.read_csv('/content/drive/My Drive/my_data.csv')
    print("Data loaded successfully:")
    display(df.head())
except FileNotFoundError:
    print("Error: 'my_data.csv' not found. Please check the file path in your Google Drive.")
except Exception as e:
    print(f"An error occurred: {e}")

Error: 'my_data.csv' not found. Please check the file path in your Google Drive.

In [ ]:
df.head(20)

,Loan ID,Customer ID,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,f738779f-c726-40dc-92cf-689d73af533d,ded0b3c3-6bf4-4091-8726-47039f2c1b90,611314.0,Short Term,747.0,2074116.0,10+ years,Home Mortgage,Debt Consolidation,42000.83,21.8,NaN,9.0,0.0,621908.0,1058970.0,0.0,0.0
1,6dcc0947-164d-476c-a1de-3ae7283dde0a,1630e6e3-34e3-461a-8fda-09297d3140c8,266662.0,Short Term,734.0,1919190.0,10+ years,Home Mortgage,Debt Consolidation,36624.40,19.4,NaN,11.0,0.0,679573.0,904442.0,0.0,0.0
2,f7744d01-894b-49c3-8777-fc6431a2cff1,2c60938b-ad2b-4702-804d-eeca43949c52,153494.0,Short Term,709.0,871112.0,2 years,Rent,Debt Consolidation,8391.73,12.5,10.0,10.0,0.0,38532.0,388036.0,0.0,0.0
3,83721ffb-b99a-4a0f-aea5-ef472a138b41,12116614-2f3c-4d16-ad34-d92883718806,176242.0,Short Term,727.0,780083.0,10+ years,Rent,Debt Consolidation,16771.87,16.5,27.0,16.0,1.0,156940.0,531322.0,1.0,0.0
4,08f3789f-5714-4b10-929d-e1527ab5e5a3,39888105-fd5f-4023-860a-30a3e6f5ccb7,321992.0,Short Term,744.0,1761148.0,10+ years,Home Mortgage,Debt Consolidation,39478.77,26.0,44.0,14.0,0.0,359765.0,468072.0,0.0,0.0
5,a4957169-d809-44cc-847b-975400bc8d11,6878d414-6a22-4712-ae43-9b3f798e463a,202928.0,Short Term,741.0,760380.0,1 year,Rent,Debt Consolidation,6526.69,13.8,NaN,6.0,0.0,258647.0,476872.0,0.0,0.0
6,43467302-94fe-494b-b52f-3fd891fea71c,48113a98-a4a0-4956-b57d-f0ce344826fb,621786.0,Long Term,733.0,1783606.0,10+ years,Home Mortgage,Debt Consolidation,36563.98,15.3,NaN,42.0,0.0,281599.0,1449162.0,0.0,0.0
7,930c7cb3-6086-434a-9547-3ed41c181552,19941661-98e2-4800-93c9-a0e92057c813,266794.0,Long Term,NaN,NaN,< 1 year,Own Home,Debt Consolidation,12336.89,5.8,NaN,9.0,0.0,233206.0,342232.0,0.0,0.0
8,0b2f1b66-741e-4e37-a929-99926cdc9e9a,6a1adeda-079b-49e5-ac7c-91828f2806a0,202466.0,Short Term,736.0,1068617.0,5 years,Rent,Debt Consolidation,18745.21,20.5,NaN,2.0,0.0,0.0,0.0,0.0,0.0
9,d08f3a5e-93df-40e7-bdd8-cba59180bddf,4080a828-a61a-4f04-a627-397f4319500c,266288.0,Long Term,683.0,2031518.0,2 years,Rent,Debt Consolidation,12443.10,24.4,56.0,8.0,2.0,31445.0,251130.0,2.0,0.0
10,3102b699-a2d2-4df4-9c33-005dc41e3525,8116b23d-aad4-436f-9666-e99b28c21b05,121110.0,Short Term,NaN,NaN,< 1 year,Rent,Debt Consolidation,10749.44,19.2,52.0,4.0,0.0,102087.0,198330.0,0.0,0.0
11,663ad9a3-4691-4f8c-90c6-75a5f4f0b34f,8ec9f388-a275-40ee-9edc-82dec9f978c3,258104.0,Short Term,723.0,1284514.0,7 years,Rent,Debt Consolidation,6368.99,14.6,64.0,12.0,0.0,128402.0,266904.0,0.0,0.0
12,1e277d73-10b5-475f-8538-2a5a09d62c8d,db6fb330-9742-4738-a35f-810f9573684c,161722.0,Short Term,680.0,504374.0,7 years,Rent,other,6094.63,9.5,NaN,13.0,0.0,167903.0,388828.0,0.0,0.0
13,79d992b7-0aa7-4059-a10b-3d416809d77e,3baae7fe-d27a-40af-9289-2b4626c0893f,753016.0,Long Term,NaN,NaN,5 years,Home Mortgage,Debt Consolidation,9627.49,21.7,21.0,9.0,0.0,384522.0,657646.0,0.0,0.0
14,c3c63911-be01-410b-a20a-85cb9bb83712,622add56-97b2-4067-88c7-55eafff12017,444664.0,Short Term,NaN,NaN,5 years,Rent,Debt Consolidation,22817.86,17.9,8.0,25.0,0.0,318953.0,971872.0,0.0,0.0
15,a913063f-af67-4a8d-b663-e83b9085180d,4f8389cd-2ac7-40f6-a2bc-5c545838953f,172282.0,Short Term,696.0,669560.0,3 years,Home Mortgage,Debt Consolidation,17966.78,18.2,NaN,16.0,0.0,431490.0,999262.0,0.0,0.0
16,e326b52a-66a2-4155-925a-91dcefa97c8a,8c49e3f3-bf36-434d-a518-145c825d9455,275440.0,Short Term,729.0,1236976.0,6 years,Rent,Debt Consolidation,21647.08,35.8,NaN,13.0,0.0,151088.0,264242.0,0.0,0.0
17,add946a5-20a5-4211-bf22-408525123b1d,163b8125-8f24-4b8f-ba59-23ea017f5b48,218834.0,Short Term,742.0,1077262.0,3 years,Own Home,Home Improvements,19390.64,24.5,29.0,37.0,0.0,212800.0,502876.0,0.0,0.0
18,cb6f7b00-62e7-4e18-8e73-73e60396e270,ce6fc244-b9a8-44b8-95f4-61c41ed5d03b,99999999.0,Short Term,715.0,442339.0,< 1 year,Rent,Debt Consolidation,14007.18,17.0,25.0,14.0,0.0,65474.0,284966.0,0.0,0.0
19,e6246fe9-6b7b-448c-a817-f91b58199e32,bcace9c1-a4c0-4d6d-9582-fa2026c3fc0b,99999999.0,Long Term,715.0,694526.0,8 years,Rent,Debt Consolidation,4358.22,17.3,47.0,5.0,0.0,137332.0,272734.0,0.0,0.0

In [ ]:
df = df.dropna(how='all')
num_cols = ['Credit Score', 'Annual Income']
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())
df['Years in current job'] = df['Years in current job'].fillna(df['Years in current job'].mode()[0])
zero_fill_cols = ['Months since last delinquent', 'Bankruptcies', 'Tax Liens']
df[zero_fill_cols] = df[zero_fill_cols].fillna(0)

In [ ]:
df.head(50)

,Loan ID,Customer ID,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,f738779f-c726-40dc-92cf-689d73af533d,ded0b3c3-6bf4-4091-8726-47039f2c1b90,611314.0,Short Term,747.0,2074116.0,10+ years,Home Mortgage,Debt Consolidation,42000.83,21.8,0.0,9.0,0.0,621908.0,1058970.0,0.0,0.0
1,6dcc0947-164d-476c-a1de-3ae7283dde0a,1630e6e3-34e3-461a-8fda-09297d3140c8,266662.0,Short Term,734.0,1919190.0,10+ years,Home Mortgage,Debt Consolidation,36624.40,19.4,0.0,11.0,0.0,679573.0,904442.0,0.0,0.0
2,f7744d01-894b-49c3-8777-fc6431a2cff1,2c60938b-ad2b-4702-804d-eeca43949c52,153494.0,Short Term,709.0,871112.0,2 years,Rent,Debt Consolidation,8391.73,12.5,10.0,10.0,0.0,38532.0,388036.0,0.0,0.0
3,83721ffb-b99a-4a0f-aea5-ef472a138b41,12116614-2f3c-4d16-ad34-d92883718806,176242.0,Short Term,727.0,780083.0,10+ years,Rent,Debt Consolidation,16771.87,16.5,27.0,16.0,1.0,156940.0,531322.0,1.0,0.0
4,08f3789f-5714-4b10-929d-e1527ab5e5a3,39888105-fd5f-4023-860a-30a3e6f5ccb7,321992.0,Short Term,744.0,1761148.0,10+ years,Home Mortgage,Debt Consolidation,39478.77,26.0,44.0,14.0,0.0,359765.0,468072.0,0.0,0.0
5,a4957169-d809-44cc-847b-975400bc8d11,6878d414-6a22-4712-ae43-9b3f798e463a,202928.0,Short Term,741.0,760380.0,1 year,Rent,Debt Consolidation,6526.69,13.8,0.0,6.0,0.0,258647.0,476872.0,0.0,0.0
6,43467302-94fe-494b-b52f-3fd891fea71c,48113a98-a4a0-4956-b57d-f0ce344826fb,621786.0,Long Term,733.0,1783606.0,10+ years,Home Mortgage,Debt Consolidation,36563.98,15.3,0.0,42.0,0.0,281599.0,1449162.0,0.0,0.0
7,930c7cb3-6086-434a-9547-3ed41c181552,19941661-98e2-4800-93c9-a0e92057c813,266794.0,Long Term,725.0,1168272.0,< 1 year,Own Home,Debt Consolidation,12336.89,5.8,0.0,9.0,0.0,233206.0,342232.0,0.0,0.0
8,0b2f1b66-741e-4e37-a929-99926cdc9e9a,6a1adeda-079b-49e5-ac7c-91828f2806a0,202466.0,Short Term,736.0,1068617.0,5 years,Rent,Debt Consolidation,18745.21,20.5,0.0,2.0,0.0,0.0,0.0,0.0,0.0
9,d08f3a5e-93df-40e7-bdd8-cba59180bddf,4080a828-a61a-4f04-a627-397f4319500c,266288.0,Long Term,683.0,2031518.0,2 years,Rent,Debt Consolidation,12443.10,24.4,56.0,8.0,2.0,31445.0,251130.0,2.0,0.0
10,3102b699-a2d2-4df4-9c33-005dc41e3525,8116b23d-aad4-436f-9666-e99b28c21b05,121110.0,Short Term,725.0,1168272.0,< 1 year,Rent,Debt Consolidation,10749.44,19.2,52.0,4.0,0.0,102087.0,198330.0,0.0,0.0
11,663ad9a3-4691-4f8c-90c6-75a5f4f0b34f,8ec9f388-a275-40ee-9edc-82dec9f978c3,258104.0,Short Term,723.0,1284514.0,7 years,Rent,Debt Consolidation,6368.99,14.6,64.0,12.0,0.0,128402.0,266904.0,0.0,0.0
12,1e277d73-10b5-475f-8538-2a5a09d62c8d,db6fb330-9742-4738-a35f-810f9573684c,161722.0,Short Term,680.0,504374.0,7 years,Rent,other,6094.63,9.5,0.0,13.0,0.0,167903.0,388828.0,0.0,0.0
13,79d992b7-0aa7-4059-a10b-3d416809d77e,3baae7fe-d27a-40af-9289-2b4626c0893f,753016.0,Long Term,725.0,1168272.0,5 years,Home Mortgage,Debt Consolidation,9627.49,21.7,21.0,9.0,0.0,384522.0,657646.0,0.0,0.0
14,c3c63911-be01-410b-a20a-85cb9bb83712,622add56-97b2-4067-88c7-55eafff12017,444664.0,Short Term,725.0,1168272.0,5 years,Rent,Debt Consolidation,22817.86,17.9,8.0,25.0,0.0,318953.0,971872.0,0.0,0.0
15,a913063f-af67-4a8d-b663-e83b9085180d,4f8389cd-2ac7-40f6-a2bc-5c545838953f,172282.0,Short Term,696.0,669560.0,3 years,Home Mortgage,Debt Consolidation,17966.78,18.2,0.0,16.0,0.0,431490.0,999262.0,0.0,0.0
16,e326b52a-66a2-4155-925a-91dcefa97c8a,8c49e3f3-bf36-434d-a518-145c825d9455,275440.0,Short Term,729.0,1236976.0,6 years,Rent,Debt Consolidation,21647.08,35.8,0.0,13.0,0.0,151088.0,264242.0,0.0,0.0
17,add946a5-20a5-4211-bf22-408525123b1d,163b8125-8f24-4b8f-ba59-23ea017f5b48,218834.0,Short Term,742.0,1077262.0,3 years,Own Home,Home Improvements,19390.64,24.5,29.0,37.0,0.0,212800.0,502876.0,0.0,0.0
18,cb6f7b00-62e7-4e18-8e73-73e60396e270,ce6fc244-b9a8-44b8-95f4-61c41ed5d03b,99999999.0,Short Term,715.0,442339.0,< 1 year,Rent,Debt Consolidation,14007.18,17.0,25.0,14.0,0.0,65474.0,284966.0,0.0,0.0
19,e6246fe9-6b7b-448c-a817-f91b58199e32,bcace9c1-a4c0-4d6d-9582-fa2026c3fc0b,99999999.0,Long Term,715.0,694526.0,8 years,Rent,Debt Consolidation,4358.22,17.3,47.0,5.0,0.0,137332.0,272734.0,0.0,0.0
20,ebefe6f6-41d6-4903-a694-7e98d69ab755,bd73b695-0960-4c46-a723-4a4cc67135eb,346610.0,Short Term,744.0,2245116.0,2 years,Home Mortgage,Debt Consolidation,24134.94,17.6,68.0,14.0,0.0,729695.0,1307922.0,0.0,0.0
21,eda0e007-b2b1-486a-b4ce-58adefd6c0bd,6518287d-d7df-4cba-8093-4abea80fb718,99999999.0,Short Term,747.0,1394676.0,5 years,Home Mortgage,Other,5834.33,31.9,0.0,7.0,0.0,164350.0,569778.0,0.0,0.0
22,82bf9406-2a78-4db2-ac3f-05b024cfbb54,63e691e6-bf28-48fc-9f54-3bc72945a9bb,219648.0,Long Term,722.0,682898.0,10+ years,Home Mortgage,Debt Consolidation,18893.79,15.5,0.0,8.0,0.0,347396.0,553300.0,0.0,0.0
23,5dfdc862-7427-4cb7-ae6a-a6b8c9f9eae2,61d66434-3514-4f9f-acb6-0ccdee208265,334620.0,Short Term,740.0,963300.0,10+ years,Home Mortgage,Debt Consolidation,16536.65,16.4,55.0,17.0,0.0,330581.0,843128.0,0.0,0.0
24,c5dca97f-d869-458b-ad84-b12093926dd4,85e3fb12-9733-40d0-ba40-c4c70a4d676f,219868.0,Short Term,736.0,683582.0,6 years,Own Home,Debt Consolidation,9057.49,9.6,0.0,8.0,0.0,121467.0,215380.0,0.0,0.0
25,0905734d-fa9f-42fe-a612-b653393ef027,c97bf871-37f7-4e65-bb79-c6eaa1d2f0b2,222816.0,Long Term,708.0,990185.0,4 years,Home Mortgage,Debt Consolidation,6031.93,17.5,0.0,8.0,1.0,125020.0,343860.0,1.0,0.0
26,10d9c56c-56f9-4a82-ad94-e95ecc25a58a,aae249a1-98dc-4423-bc3f-63142c9ad00d,108416.0,Short Term,725.0,1168272.0,10+ years,Rent,Debt Consolidation,41882.46,20.4,0.0,11.0,0.0,827051.0,1003816.0,0.0,0.0
27,ac8e5698-16a9-46f0-8b57-3fa2e145f8fd,9a561b03-ce0c-411e-85b4-73a108718cb7,108152.0,Short Term,705.0,747156.0,4 years,Rent,Business Loan,20235.38,19.9,15.0,14.0,0.0,174344.0,348062.0,0.0,0.0
28,a656f70b-632d-4513-a20b-88f1edf2c21e,3b69f3b7-4675-4bec-be5c-332d729b284c,174724.0,Short Term,725.0,1168272.0,5 years,Rent,Debt Consolidation,11341.29,8.2,0.0,4.0,0.0,85633.0,126632.0,0.0,0.0
29,6b3d25b3-33b8-41e3-9995-d6a274ac5844,3d5b68c4-e36c-4562-ac2e-1845c8a3f138,404008.0,Long Term,725.0,1168272.0,6 years,Home Mortgage,Debt Consolidation,42159.86,15.9,0.0,16.0,0.0,684950.0,1054636.0,0.0,0.0
30,af0a5a13-350d-4540-a254-c32545ebe2cb,322fdfe1-0113-4a84-8a6d-e93dcfe5d7e2,360228.0,Short Term,740.0,2138906.0,10+ years,Home Mortgage,Debt Consolidation,27984.15,15.5,18.0,8.0,0.0,164008.0,225280.0,0.0,0.0
31,d4407af5-9e67-4465-9415-94c3b9575ea4,7883d485-cd19-4e74-84e6-183b0f239996,218724.0,Short Term,725.0,1168272.0,< 1 year,HaveMortgage,Take a Trip,4967.36,11.0,6.0,7.0,0.0,16511.0,108064.0,0.0,0.0
32,65d23a2f-1818-4cfb-923d-75bdb52013f4,6866ead5-79d6-4102-ac08-a861281efafe,441012.0,Short Term,738.0,979716.0,10+ years,Rent,Debt Consolidation,12899.67,27.3,0.0,11.0,0.0,380228.0,608938.0,0.0,0.0
33,f95c766b-55ca-43a7-966c-67a3ad82e142,481df4a0-f256-4c49-92db-8ae7a5642bdf,337370.0,Long Term,717.0,1146004.0,1 year,Rent,Debt Consolidation,14802.33,21.0,32.0,9.0,0.0,256139.0,423104.0,0.0,0.0
34,cc43b784-97e5-4a6d-a75d-1e03f7d059dd,54459ce0-50d7-4957-8f18-e35f4b49214d,765688.0,Long Term,706.0,5951484.0,3 years,Rent,small_business,61498.63,22.4,0.0,13.0,0.0,549100.0,1464980.0,0.0,0.0
35,f8fa11bd-d0d2-4c9f-998e-9f9d866803a7,ab86ebb2-c4f4-47dd-b430-3d6270394f8b,468908.0,Long Term,6470.0,1833842.0,8 years,Rent,other,5898.93,14.4,0.0,19.0,1.0,183863.0,809490.0,1.0,0.0
36,875c3df0-d022-4aa5-aced-8f29d6722489,1b233b3a-bf6e-478a-be2e-673feb2f5843,219428.0,Short Term,712.0,1301671.0,10+ years,Rent,Debt Consolidation,22237.03,15.6,0.0,9.0,0.0,458679.0,624096.0,0.0,0.0
37,769e4e52-d0e7-435c-a87d-1dbf2daaaf94,401b284d-0f6a-443f-84be-b79e8df33620,574904.0,Short Term,706.0,1306592.0,9 years,Rent,other,8078.99,14.0,0.0,4.0,0.0,1596.0,306196.0,0.0,0.0
38,41e8f5a6-78a8-4f1b-9de3-4c6079d52076,3c6cdac9-88c7-4fa1-a5a1-18de2e1a3097,401192.0,Short Term,704.0,1539912.0,10+ years,Rent,Debt Consolidation,27500.41,22.0,0.0,18.0,0.0,423092.0,769054.0,0.0,0.0
39,c3552bfe-912d-42f2-b25e-73d899e0de8b,b171374b-7aa3-42bb-b242-3bca259f8f28,257444.0,Short Term,736.0,648508.0,10+ years,Rent,Debt Consolidation,5944.53,17.5,46.0,10.0,0.0,204516.0,621566.0,0.0,0.0
40,89dbf9cb-714a-44de-9412-add4e3e85c45,16f4e4a9-6a99-417e-9c31-89579951083b,309694.0,Long Term,725.0,1168272.0,10+ years,Own Home,Debt Consolidation,23473.17,26.0,38.0,10.0,0.0,402059.0,650188.0,0.0,0.0
41,dd80a04f-e1d4-4182-9bf7-a1966558e28a,55cedc7a-f5b2-4ac7-a7ef-bb2eb635ba90,214258.0,Short Term,725.0,1168272.0,1 year,Rent,Debt Consolidation,7207.46,12.8,69.0,10.0,1.0,209361.0,338580.0,0.0,0.0
42,4066eff2-4f29-48dd-9408-9c0cc68afc42,23bb03ea-cee4-420f-aae0-5a99e05c62a6,325754.0,Short Term,725.0,1168272.0,4 years,Home Mortgage,Debt Consolidation,14301.30,25.0,13.0,11.0,0.0,165186.0,466532.0,0.0,0.0
43,a652d67e-e99d-46d7-b8c4-aba02bfe3403,4aec62aa-c53f-4779-9535-c5f9d3925976,651354.0,Short Term,725.0,1168272.0,10+ years,Home Mortgage,Home Improvements,32314.25,19.1,37.0,21.0,0.0,356687.0,1868768.0,0.0,0.0
44,628dd91e-2c5e-4a07-b5f5-00b4cbc93253,cef6a8aa-4821-4e14-a03e-75c2f1490049,262108.0,Short Term,733.0,855342.0,7 years,Rent,Debt Consolidation,9194.86,22.8,0.0,5.0,0.0,110884.0,224840.0,0.0,0.0
45,1e5e3699-94cc-4887-ba33-29d0b1096a15,67a35b69-620c-4498-8325-cd9bd20c33c3,310376.0,Short Term,725.0,1168272.0,2 years,Rent,Debt Consolidation,5101.12,8.5,0.0,10.0,0.0,126179.0,241890.0,0.0,0.0
46,b69432ba-4651-415b-9fe1-200469d3c9fd,75a48dbf-05c4-4ef4-bbe1-1a54a52b2d39,429616.0,Short Term,725.0,1168272.0,10+ years,Home Mortgage,Debt Consolidation,21998.58,22.3,25.0,12.0,0.0,321898.0,847066.0,0.0,0.0
47,2f5d0697-7dbb-44b2-9bd4-db4a51370f61,6bdae209-f82f-4c2d-9be3-17af444c5b44,414744.0,Short Term,706.0,1164225.0,10+ years,Rent,Debt Consolidation,14746.66,10.5,0.0,17.0,0.0,258172.0,797170.0,0.0,0.0
48,8ab9234f-3964-4c1c-bda0-d993fbd62f24,5ef6d424-eada-4bab-8904-4f7f26523c92,654126.0,Long Term,646.0,2504504.0,9 years,Home Mortgage,other,14818.48,31.9,11.0,7.0,0.0,130264.0,187594.0,0.0,0.0
49,42a25517-cef8-41d4-b56e-629e17618252,395a76dd-8ad0-45fb-ae56-bd848e300352,539990.0,Long Term,682.0,1790807.0,2 years,Home Mortgage,Debt Consolidation,24026.64,17.3,53.0,13.0,1.0,81358.0,382910.0,1.0,0.0

In [ ]:
print(df.isnull().sum)

<bound method DataFrame.sum of       Loan ID  Customer ID  Current Loan Amount   Term  Credit Score  \
0       False        False                False  False         False
1       False        False                False  False         False
2       False        False                False  False         False
3       False        False                False  False         False
4       False        False                False  False         False
...       ...          ...                  ...    ...           ...
9995    False        False                False  False         False
9996    False        False                False  False         False
9997    False        False                False  False         False
9998    False        False                False  False         False
9999    False        False                False  False         False

      Annual Income  Years in current job  Home Ownership  Purpose  \
0             False                 False           False    False
1             False                 False           False    False
2             False                 False           False    False
3             False                 False           False    False
4             False                 False           False    False
...             ...                   ...             ...      ...
9995          False                 False           False    False
9996          False                 False           False    False
9997          False                 False           False    False
9998          False                 False           False    False
9999          False                 False           False    False

      Monthly Debt  Years of Credit History  Months since last delinquent  \
0            False                    False                         False
1            False                    False                         False
2            False                    False                         False
3            False                    False                         False
4            False                    False                         False
...            ...                      ...                           ...
9995         False                    False                         False
9996         False                    False                         False
9997         False                    False                         False
9998         False                    False                         False
9999         False                    False                         False

      Number of Open Accounts  Number of Credit Problems  \
0                       False                      False
1                       False                      False
2                       False                      False
3                       False                      False
4                       False                      False
...                       ...                        ...
9995                    False                      False
9996                    False                      False
9997                    False                      False
9998                    False                      False
9999                    False                      False

      Current Credit Balance  Maximum Open Credit  Bankruptcies  Tax Liens
0                      False                False         False      False
1                      False                False         False      False
2                      False                False         False      False
3                      False                False         False      False
4                      False                False         False      False
...                      ...                  ...           ...        ...
9995                   False                False         False      False
9996                   False                False         False      False
9997                   False                False         False      False
9998                   False                False         False      False
9999                   False                False         False      False

[10000 rows x 18 columns]>

In [ ]:
df.loc[df['Credit Score'] > 850, 'Credit Score'] = df['Credit Score'] / 10

In [ ]:
import numpy as np
median_loan = df[df['Current Loan Amount'] < 99999999]['Current Loan Amount'].median()
df['Current Loan Amount'] = df['Current Loan Amount'].replace(99999999, median_loan)

In [ ]:
df.head(60)

,Loan ID,Customer ID,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,f738779f-c726-40dc-92cf-689d73af533d,ded0b3c3-6bf4-4091-8726-47039f2c1b90,611314.0,Short Term,747.0,2074116.0,10+ years,Home Mortgage,Debt Consolidation,42000.83,21.8,0.0,9.0,0.0,621908.0,1058970.0,0.0,0.0
1,6dcc0947-164d-476c-a1de-3ae7283dde0a,1630e6e3-34e3-461a-8fda-09297d3140c8,266662.0,Short Term,734.0,1919190.0,10+ years,Home Mortgage,Debt Consolidation,36624.40,19.4,0.0,11.0,0.0,679573.0,904442.0,0.0,0.0
2,f7744d01-894b-49c3-8777-fc6431a2cff1,2c60938b-ad2b-4702-804d-eeca43949c52,153494.0,Short Term,709.0,871112.0,2 years,Rent,Debt Consolidation,8391.73,12.5,10.0,10.0,0.0,38532.0,388036.0,0.0,0.0
3,83721ffb-b99a-4a0f-aea5-ef472a138b41,12116614-2f3c-4d16-ad34-d92883718806,176242.0,Short Term,727.0,780083.0,10+ years,Rent,Debt Consolidation,16771.87,16.5,27.0,16.0,1.0,156940.0,531322.0,1.0,0.0
4,08f3789f-5714-4b10-929d-e1527ab5e5a3,39888105-fd5f-4023-860a-30a3e6f5ccb7,321992.0,Short Term,744.0,1761148.0,10+ years,Home Mortgage,Debt Consolidation,39478.77,26.0,44.0,14.0,0.0,359765.0,468072.0,0.0,0.0
5,a4957169-d809-44cc-847b-975400bc8d11,6878d414-6a22-4712-ae43-9b3f798e463a,202928.0,Short Term,741.0,760380.0,1 year,Rent,Debt Consolidation,6526.69,13.8,0.0,6.0,0.0,258647.0,476872.0,0.0,0.0
6,43467302-94fe-494b-b52f-3fd891fea71c,48113a98-a4a0-4956-b57d-f0ce344826fb,621786.0,Long Term,733.0,1783606.0,10+ years,Home Mortgage,Debt Consolidation,36563.98,15.3,0.0,42.0,0.0,281599.0,1449162.0,0.0,0.0
7,930c7cb3-6086-434a-9547-3ed41c181552,19941661-98e2-4800-93c9-a0e92057c813,266794.0,Long Term,725.0,1168272.0,< 1 year,Own Home,Debt Consolidation,12336.89,5.8,0.0,9.0,0.0,233206.0,342232.0,0.0,0.0
8,0b2f1b66-741e-4e37-a929-99926cdc9e9a,6a1adeda-079b-49e5-ac7c-91828f2806a0,202466.0,Short Term,736.0,1068617.0,5 years,Rent,Debt Consolidation,18745.21,20.5,0.0,2.0,0.0,0.0,0.0,0.0,0.0
9,d08f3a5e-93df-40e7-bdd8-cba59180bddf,4080a828-a61a-4f04-a627-397f4319500c,266288.0,Long Term,683.0,2031518.0,2 years,Rent,Debt Consolidation,12443.10,24.4,56.0,8.0,2.0,31445.0,251130.0,2.0,0.0
10,3102b699-a2d2-4df4-9c33-005dc41e3525,8116b23d-aad4-436f-9666-e99b28c21b05,121110.0,Short Term,725.0,1168272.0,< 1 year,Rent,Debt Consolidation,10749.44,19.2,52.0,4.0,0.0,102087.0,198330.0,0.0,0.0
11,663ad9a3-4691-4f8c-90c6-75a5f4f0b34f,8ec9f388-a275-40ee-9edc-82dec9f978c3,258104.0,Short Term,723.0,1284514.0,7 years,Rent,Debt Consolidation,6368.99,14.6,64.0,12.0,0.0,128402.0,266904.0,0.0,0.0
12,1e277d73-10b5-475f-8538-2a5a09d62c8d,db6fb330-9742-4738-a35f-810f9573684c,161722.0,Short Term,680.0,504374.0,7 years,Rent,other,6094.63,9.5,0.0,13.0,0.0,167903.0,388828.0,0.0,0.0
13,79d992b7-0aa7-4059-a10b-3d416809d77e,3baae7fe-d27a-40af-9289-2b4626c0893f,753016.0,Long Term,725.0,1168272.0,5 years,Home Mortgage,Debt Consolidation,9627.49,21.7,21.0,9.0,0.0,384522.0,657646.0,0.0,0.0
14,c3c63911-be01-410b-a20a-85cb9bb83712,622add56-97b2-4067-88c7-55eafff12017,444664.0,Short Term,725.0,1168272.0,5 years,Rent,Debt Consolidation,22817.86,17.9,8.0,25.0,0.0,318953.0,971872.0,0.0,0.0
15,a913063f-af67-4a8d-b663-e83b9085180d,4f8389cd-2ac7-40f6-a2bc-5c545838953f,172282.0,Short Term,696.0,669560.0,3 years,Home Mortgage,Debt Consolidation,17966.78,18.2,0.0,16.0,0.0,431490.0,999262.0,0.0,0.0
16,e326b52a-66a2-4155-925a-91dcefa97c8a,8c49e3f3-bf36-434d-a518-145c825d9455,275440.0,Short Term,729.0,1236976.0,6 years,Rent,Debt Consolidation,21647.08,35.8,0.0,13.0,0.0,151088.0,264242.0,0.0,0.0
17,add946a5-20a5-4211-bf22-408525123b1d,163b8125-8f24-4b8f-ba59-23ea017f5b48,218834.0,Short Term,742.0,1077262.0,3 years,Own Home,Home Improvements,19390.64,24.5,29.0,37.0,0.0,212800.0,502876.0,0.0,0.0
18,cb6f7b00-62e7-4e18-8e73-73e60396e270,ce6fc244-b9a8-44b8-95f4-61c41ed5d03b,265958.0,Short Term,715.0,442339.0,< 1 year,Rent,Debt Consolidation,14007.18,17.0,25.0,14.0,0.0,65474.0,284966.0,0.0,0.0
19,e6246fe9-6b7b-448c-a817-f91b58199e32,bcace9c1-a4c0-4d6d-9582-fa2026c3fc0b,265958.0,Long Term,715.0,694526.0,8 years,Rent,Debt Consolidation,4358.22,17.3,47.0,5.0,0.0,137332.0,272734.0,0.0,0.0
20,ebefe6f6-41d6-4903-a694-7e98d69ab755,bd73b695-0960-4c46-a723-4a4cc67135eb,346610.0,Short Term,744.0,2245116.0,2 years,Home Mortgage,Debt Consolidation,24134.94,17.6,68.0,14.0,0.0,729695.0,1307922.0,0.0,0.0
21,eda0e007-b2b1-486a-b4ce-58adefd6c0bd,6518287d-d7df-4cba-8093-4abea80fb718,265958.0,Short Term,747.0,1394676.0,5 years,Home Mortgage,Other,5834.33,31.9,0.0,7.0,0.0,164350.0,569778.0,0.0,0.0
22,82bf9406-2a78-4db2-ac3f-05b024cfbb54,63e691e6-bf28-48fc-9f54-3bc72945a9bb,219648.0,Long Term,722.0,682898.0,10+ years,Home Mortgage,Debt Consolidation,18893.79,15.5,0.0,8.0,0.0,347396.0,553300.0,0.0,0.0
23,5dfdc862-7427-4cb7-ae6a-a6b8c9f9eae2,61d66434-3514-4f9f-acb6-0ccdee208265,334620.0,Short Term,740.0,963300.0,10+ years,Home Mortgage,Debt Consolidation,16536.65,16.4,55.0,17.0,0.0,330581.0,843128.0,0.0,0.0
24,c5dca97f-d869-458b-ad84-b12093926dd4,85e3fb12-9733-40d0-ba40-c4c70a4d676f,219868.0,Short Term,736.0,683582.0,6 years,Own Home,Debt Consolidation,9057.49,9.6,0.0,8.0,0.0,121467.0,215380.0,0.0,0.0
25,0905734d-fa9f-42fe-a612-b653393ef027,c97bf871-37f7-4e65-bb79-c6eaa1d2f0b2,222816.0,Long Term,708.0,990185.0,4 years,Home Mortgage,Debt Consolidation,6031.93,17.5,0.0,8.0,1.0,125020.0,343860.0,1.0,0.0
26,10d9c56c-56f9-4a82-ad94-e95ecc25a58a,aae249a1-98dc-4423-bc3f-63142c9ad00d,108416.0,Short Term,725.0,1168272.0,10+ years,Rent,Debt Consolidation,41882.46,20.4,0.0,11.0,0.0,827051.0,1003816.0,0.0,0.0
27,ac8e5698-16a9-46f0-8b57-3fa2e145f8fd,9a561b03-ce0c-411e-85b4-73a108718cb7,108152.0,Short Term,705.0,747156.0,4 years,Rent,Business Loan,20235.38,19.9,15.0,14.0,0.0,174344.0,348062.0,0.0,0.0
28,a656f70b-632d-4513-a20b-88f1edf2c21e,3b69f3b7-4675-4bec-be5c-332d729b284c,174724.0,Short Term,725.0,1168272.0,5 years,Rent,Debt Consolidation,11341.29,8.2,0.0,4.0,0.0,85633.0,126632.0,0.0,0.0
29,6b3d25b3-33b8-41e3-9995-d6a274ac5844,3d5b68c4-e36c-4562-ac2e-1845c8a3f138,404008.0,Long Term,725.0,1168272.0,6 years,Home Mortgage,Debt Consolidation,42159.86,15.9,0.0,16.0,0.0,684950.0,1054636.0,0.0,0.0
30,af0a5a13-350d-4540-a254-c32545ebe2cb,322fdfe1-0113-4a84-8a6d-e93dcfe5d7e2,360228.0,Short Term,740.0,2138906.0,10+ years,Home Mortgage,Debt Consolidation,27984.15,15.5,18.0,8.0,0.0,164008.0,225280.0,0.0,0.0
31,d4407af5-9e67-4465-9415-94c3b9575ea4,7883d485-cd19-4e74-84e6-183b0f239996,218724.0,Short Term,725.0,1168272.0,< 1 year,HaveMortgage,Take a Trip,4967.36,11.0,6.0,7.0,0.0,16511.0,108064.0,0.0,0.0
32,65d23a2f-1818-4cfb-923d-75bdb52013f4,6866ead5-79d6-4102-ac08-a861281efafe,441012.0,Short Term,738.0,979716.0,10+ years,Rent,Debt Consolidation,12899.67,27.3,0.0,11.0,0.0,380228.0,608938.0,0.0,0.0
33,f95c766b-55ca-43a7-966c-67a3ad82e142,481df4a0-f256-4c49-92db-8ae7a5642bdf,337370.0,Long Term,717.0,1146004.0,1 year,Rent,Debt Consolidation,14802.33,21.0,32.0,9.0,0.0,256139.0,423104.0,0.0,0.0
34,cc43b784-97e5-4a6d-a75d-1e03f7d059dd,54459ce0-50d7-4957-8f18-e35f4b49214d,765688.0,Long Term,706.0,5951484.0,3 years,Rent,small_business,61498.63,22.4,0.0,13.0,0.0,549100.0,1464980.0,0.0,0.0
35,f8fa11bd-d0d2-4c9f-998e-9f9d866803a7,ab86ebb2-c4f4-47dd-b430-3d6270394f8b,468908.0,Long Term,647.0,1833842.0,8 years,Rent,other,5898.93,14.4,0.0,19.0,1.0,183863.0,809490.0,1.0,0.0
36,875c3df0-d022-4aa5-aced-8f29d6722489,1b233b3a-bf6e-478a-be2e-673feb2f5843,219428.0,Short Term,712.0,1301671.0,10+ years,Rent,Debt Consolidation,22237.03,15.6,0.0,9.0,0.0,458679.0,624096.0,0.0,0.0
37,769e4e52-d0e7-435c-a87d-1dbf2daaaf94,401b284d-0f6a-443f-84be-b79e8df33620,574904.0,Short Term,706.0,1306592.0,9 years,Rent,other,8078.99,14.0,0.0,4.0,0.0,1596.0,306196.0,0.0,0.0
38,41e8f5a6-78a8-4f1b-9de3-4c6079d52076,3c6cdac9-88c7-4fa1-a5a1-18de2e1a3097,401192.0,Short Term,704.0,1539912.0,10+ years,Rent,Debt Consolidation,27500.41,22.0,0.0,18.0,0.0,423092.0,769054.0,0.0,0.0
39,c3552bfe-912d-42f2-b25e-73d899e0de8b,b171374b-7aa3-42bb-b242-3bca259f8f28,257444.0,Short Term,736.0,648508.0,10+ years,Rent,Debt Consolidation,5944.53,17.5,46.0,10.0,0.0,204516.0,621566.0,0.0,0.0
40,89dbf9cb-714a-44de-9412-add4e3e85c45,16f4e4a9-6a99-417e-9c31-89579951083b,309694.0,Long Term,725.0,1168272.0,10+ years,Own Home,Debt Consolidation,23473.17,26.0,38.0,10.0,0.0,402059.0,650188.0,0.0,0.0
41,dd80a04f-e1d4-4182-9bf7-a1966558e28a,55cedc7a-f5b2-4ac7-a7ef-bb2eb635ba90,214258.0,Short Term,725.0,1168272.0,1 year,Rent,Debt Consolidation,7207.46,12.8,69.0,10.0,1.0,209361.0,338580.0,0.0,0.0
42,4066eff2-4f29-48dd-9408-9c0cc68afc42,23bb03ea-cee4-420f-aae0-5a99e05c62a6,325754.0,Short Term,725.0,1168272.0,4 years,Home Mortgage,Debt Consolidation,14301.30,25.0,13.0,11.0,0.0,165186.0,466532.0,0.0,0.0
43,a652d67e-e99d-46d7-b8c4-aba02bfe3403,4aec62aa-c53f-4779-9535-c5f9d3925976,651354.0,Short Term,725.0,1168272.0,10+ years,Home Mortgage,Home Improvements,32314.25,19.1,37.0,21.0,0.0,356687.0,1868768.0,0.0,0.0
44,628dd91e-2c5e-4a07-b5f5-00b4cbc93253,cef6a8aa-4821-4e14-a03e-75c2f1490049,262108.0,Short Term,733.0,855342.0,7 years,Rent,Debt Consolidation,9194.86,22.8,0.0,5.0,0.0,110884.0,224840.0,0.0,0.0
45,1e5e3699-94cc-4887-ba33-29d0b1096a15,67a35b69-620c-4498-8325-cd9bd20c33c3,310376.0,Short Term,725.0,1168272.0,2 years,Rent,Debt Consolidation,5101.12,8.5,0.0,10.0,0.0,126179.0,241890.0,0.0,0.0
46,b69432ba-4651-415b-9fe1-200469d3c9fd,75a48dbf-05c4-4ef4-bbe1-1a54a52b2d39,429616.0,Short Term,725.0,1168272.0,10+ years,Home Mortgage,Debt Consolidation,21998.58,22.3,25.0,12.0,0.0,321898.0,847066.0,0.0,0.0
47,2f5d0697-7dbb-44b2-9bd4-db4a51370f61,6bdae209-f82f-4c2d-9be3-17af444c5b44,414744.0,Short Term,706.0,1164225.0,10+ years,Rent,Debt Consolidation,14746.66,10.5,0.0,17.0,0.0,258172.0,797170.0,0.0,0.0
48,8ab9234f-3964-4c1c-bda0-d993fbd62f24,5ef6d424-eada-4bab-8904-4f7f26523c92,654126.0,Long Term,646.0,2504504.0,9 years,Home Mortgage,other,14818.48,31.9,11.0,7.0,0.0,130264.0,187594.0,0.0,0.0
49,42a25517-cef8-41d4-b56e-629e17618252,395a76dd-8ad0-45fb-ae56-bd848e300352,539990.0,Long Term,682.0,1790807.0,2 years,Home Mortgage,Debt Consolidation,24026.64,17.3,53.0,13.0,1.0,81358.0,382910.0,1.0,0.0
50,9386034f-3370-496c-8695-0082aa055281,8f36428b-2b8d-4fed-8e35-5d8a92c7cc8f,531476.0,Short Term,725.0,1168272.0,10+ years,Home Mortgage,Debt Consolidation,30122.60,26.4,0.0,26.0,0.0,658559.0,3272720.0,0.0,0.0
51,443bcf4c-2f98-42c9-8034-0870be82c4c6,5b064f68-e99a-4597-80c7-2f2ac4ebea9a,316426.0,Long Term,717.0,683183.0,1 year,Rent,Debt Consolidation,16453.24,15.0,2.0,10.0,0.0,136952.0,554488.0,0.0,0.0
52,a58abd00-1fa0-412b-8d02-4a272f3c4d66,da4fd425-7d45-4c5f-96ed-7930a056e45b,473902.0,Long Term,713.0,1042511.0,5 years,Home Mortgage,Debt Consolidation,22240.45,14.0,0.0,7.0,0.0,232655.0,386496.0,0.0,0.0
53,65688ec3-f816-4745-8eb0-79a08c41ecfd,d3790b57-80e5-45f7-8b4f-81baa72e1df1,223344.0,Short Term,716.0,1195898.0,10+ years,Rent,Debt Consolidation,11759.86,17.6,71.0,7.0,0.0,94677.0,167618.0,0.0,0.0
54,d4fe49c5-f897-4540-9366-f2099e3bc9b6,a0b2bc45-742c-441b-858e-5acbaab04147,766238.0,Long Term,649.0,1796165.0,< 1 year,Rent,Debt Consolidation,36821.24,33.1,0.0,10.0,0.0,510093.0,925760.0,0.0,0.0
55,534159bc-4ac2-4f65-9637-12ba88afa78d,5e374d0a-a7cd-4ea6-8814-00043ea61aa1,471152.0,Long Term,688.0,1017279.0,< 1 year,Rent,Debt Consolidation,14496.24,8.5,0.0,7.0,0.0,115444.0,218064.0,0.0,0.0
56,8310d972-63ad-4a60-9a79-4a75862fb5f6,ef9ddefc-a550-4245-a80f-822911c31d1f,563486.0,Short Term,747.0,2647308.0,2 years,Rent,Debt Consolidation,45666.12,16.8,0.0,26.0,0.0,137256.0,2337082.0,0.0,0.0
57,119b9755-018f-436c-aa50-0a9b4c13f0d3,746fc09f-1ef1-4083-9a2a-251d3e6608fa,219824.0,Long Term,702.0,2088328.0,< 1 year,Home Mortgage,Debt Consolidation,22275.41,21.7,0.0,13.0,1.0,155800.0,451044.0,1.0,0.0
58,61d9fcf2-81ac-409a-8582-7dbee3c2d28b,4d1fef0f-293c-4090-92be-a7fc30b34cee,304986.0,Long Term,674.0,4872778.0,3 years,Rent,Debt Consolidation,30130.01,21.9,26.0,13.0,0.0,155078.0,1081740.0,0.0,0.0
59,2948d139-5fcf-40af-9a32-7e3d0f181164,659b0c70-c16a-4e27-89cc-4843cf8e56ac,105666.0,Long Term,742.0,806170.0,4 years,Home Mortgage,Debt Consolidation,15135.78,15.9,0.0,10.0,0.0,226708.0,653026.0,0.0,0.0

In [ ]:
df.head(30)

,Loan ID,Customer ID,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,f738779f-c726-40dc-92cf-689d73af533d,ded0b3c3-6bf4-4091-8726-47039f2c1b90,611314.0,Short Term,747.0,2074116.0,10+ years,Home Mortgage,Debt Consolidation,42000.83,21.8,0.0,9.0,0.0,621908.0,1058970.0,0.0,0.0
1,6dcc0947-164d-476c-a1de-3ae7283dde0a,1630e6e3-34e3-461a-8fda-09297d3140c8,266662.0,Short Term,734.0,1919190.0,10+ years,Home Mortgage,Debt Consolidation,36624.40,19.4,0.0,11.0,0.0,679573.0,904442.0,0.0,0.0
2,f7744d01-894b-49c3-8777-fc6431a2cff1,2c60938b-ad2b-4702-804d-eeca43949c52,153494.0,Short Term,709.0,871112.0,2 years,Rent,Debt Consolidation,8391.73,12.5,10.0,10.0,0.0,38532.0,388036.0,0.0,0.0
3,83721ffb-b99a-4a0f-aea5-ef472a138b41,12116614-2f3c-4d16-ad34-d92883718806,176242.0,Short Term,727.0,780083.0,10+ years,Rent,Debt Consolidation,16771.87,16.5,27.0,16.0,1.0,156940.0,531322.0,1.0,0.0
4,08f3789f-5714-4b10-929d-e1527ab5e5a3,39888105-fd5f-4023-860a-30a3e6f5ccb7,321992.0,Short Term,744.0,1761148.0,10+ years,Home Mortgage,Debt Consolidation,39478.77,26.0,44.0,14.0,0.0,359765.0,468072.0,0.0,0.0
5,a4957169-d809-44cc-847b-975400bc8d11,6878d414-6a22-4712-ae43-9b3f798e463a,202928.0,Short Term,741.0,760380.0,1 year,Rent,Debt Consolidation,6526.69,13.8,0.0,6.0,0.0,258647.0,476872.0,0.0,0.0
6,43467302-94fe-494b-b52f-3fd891fea71c,48113a98-a4a0-4956-b57d-f0ce344826fb,621786.0,Long Term,733.0,1783606.0,10+ years,Home Mortgage,Debt Consolidation,36563.98,15.3,0.0,42.0,0.0,281599.0,1449162.0,0.0,0.0
7,930c7cb3-6086-434a-9547-3ed41c181552,19941661-98e2-4800-93c9-a0e92057c813,266794.0,Long Term,725.0,1168272.0,< 1 year,Own Home,Debt Consolidation,12336.89,5.8,0.0,9.0,0.0,233206.0,342232.0,0.0,0.0
8,0b2f1b66-741e-4e37-a929-99926cdc9e9a,6a1adeda-079b-49e5-ac7c-91828f2806a0,202466.0,Short Term,736.0,1068617.0,5 years,Rent,Debt Consolidation,18745.21,20.5,0.0,2.0,0.0,0.0,0.0,0.0,0.0
9,d08f3a5e-93df-40e7-bdd8-cba59180bddf,4080a828-a61a-4f04-a627-397f4319500c,266288.0,Long Term,683.0,2031518.0,2 years,Rent,Debt Consolidation,12443.10,24.4,56.0,8.0,2.0,31445.0,251130.0,2.0,0.0
10,3102b699-a2d2-4df4-9c33-005dc41e3525,8116b23d-aad4-436f-9666-e99b28c21b05,121110.0,Short Term,725.0,1168272.0,< 1 year,Rent,Debt Consolidation,10749.44,19.2,52.0,4.0,0.0,102087.0,198330.0,0.0,0.0
11,663ad9a3-4691-4f8c-90c6-75a5f4f0b34f,8ec9f388-a275-40ee-9edc-82dec9f978c3,258104.0,Short Term,723.0,1284514.0,7 years,Rent,Debt Consolidation,6368.99,14.6,64.0,12.0,0.0,128402.0,266904.0,0.0,0.0
12,1e277d73-10b5-475f-8538-2a5a09d62c8d,db6fb330-9742-4738-a35f-810f9573684c,161722.0,Short Term,680.0,504374.0,7 years,Rent,other,6094.63,9.5,0.0,13.0,0.0,167903.0,388828.0,0.0,0.0
13,79d992b7-0aa7-4059-a10b-3d416809d77e,3baae7fe-d27a-40af-9289-2b4626c0893f,753016.0,Long Term,725.0,1168272.0,5 years,Home Mortgage,Debt Consolidation,9627.49,21.7,21.0,9.0,0.0,384522.0,657646.0,0.0,0.0
14,c3c63911-be01-410b-a20a-85cb9bb83712,622add56-97b2-4067-88c7-55eafff12017,444664.0,Short Term,725.0,1168272.0,5 years,Rent,Debt Consolidation,22817.86,17.9,8.0,25.0,0.0,318953.0,971872.0,0.0,0.0
15,a913063f-af67-4a8d-b663-e83b9085180d,4f8389cd-2ac7-40f6-a2bc-5c545838953f,172282.0,Short Term,696.0,669560.0,3 years,Home Mortgage,Debt Consolidation,17966.78,18.2,0.0,16.0,0.0,431490.0,999262.0,0.0,0.0
16,e326b52a-66a2-4155-925a-91dcefa97c8a,8c49e3f3-bf36-434d-a518-145c825d9455,275440.0,Short Term,729.0,1236976.0,6 years,Rent,Debt Consolidation,21647.08,35.8,0.0,13.0,0.0,151088.0,264242.0,0.0,0.0
17,add946a5-20a5-4211-bf22-408525123b1d,163b8125-8f24-4b8f-ba59-23ea017f5b48,218834.0,Short Term,742.0,1077262.0,3 years,Own Home,Home Improvements,19390.64,24.5,29.0,37.0,0.0,212800.0,502876.0,0.0,0.0
18,cb6f7b00-62e7-4e18-8e73-73e60396e270,ce6fc244-b9a8-44b8-95f4-61c41ed5d03b,265958.0,Short Term,715.0,442339.0,< 1 year,Rent,Debt Consolidation,14007.18,17.0,25.0,14.0,0.0,65474.0,284966.0,0.0,0.0
19,e6246fe9-6b7b-448c-a817-f91b58199e32,bcace9c1-a4c0-4d6d-9582-fa2026c3fc0b,265958.0,Long Term,715.0,694526.0,8 years,Rent,Debt Consolidation,4358.22,17.3,47.0,5.0,0.0,137332.0,272734.0,0.0,0.0
20,ebefe6f6-41d6-4903-a694-7e98d69ab755,bd73b695-0960-4c46-a723-4a4cc67135eb,346610.0,Short Term,744.0,2245116.0,2 years,Home Mortgage,Debt Consolidation,24134.94,17.6,68.0,14.0,0.0,729695.0,1307922.0,0.0,0.0
21,eda0e007-b2b1-486a-b4ce-58adefd6c0bd,6518287d-d7df-4cba-8093-4abea80fb718,265958.0,Short Term,747.0,1394676.0,5 years,Home Mortgage,Other,5834.33,31.9,0.0,7.0,0.0,164350.0,569778.0,0.0,0.0
22,82bf9406-2a78-4db2-ac3f-05b024cfbb54,63e691e6-bf28-48fc-9f54-3bc72945a9bb,219648.0,Long Term,722.0,682898.0,10+ years,Home Mortgage,Debt Consolidation,18893.79,15.5,0.0,8.0,0.0,347396.0,553300.0,0.0,0.0
23,5dfdc862-7427-4cb7-ae6a-a6b8c9f9eae2,61d66434-3514-4f9f-acb6-0ccdee208265,334620.0,Short Term,740.0,963300.0,10+ years,Home Mortgage,Debt Consolidation,16536.65,16.4,55.0,17.0,0.0,330581.0,843128.0,0.0,0.0
24,c5dca97f-d869-458b-ad84-b12093926dd4,85e3fb12-9733-40d0-ba40-c4c70a4d676f,219868.0,Short Term,736.0,683582.0,6 years,Own Home,Debt Consolidation,9057.49,9.6,0.0,8.0,0.0,121467.0,215380.0,0.0,0.0
25,0905734d-fa9f-42fe-a612-b653393ef027,c97bf871-37f7-4e65-bb79-c6eaa1d2f0b2,222816.0,Long Term,708.0,990185.0,4 years,Home Mortgage,Debt Consolidation,6031.93,17.5,0.0,8.0,1.0,125020.0,343860.0,1.0,0.0
26,10d9c56c-56f9-4a82-ad94-e95ecc25a58a,aae249a1-98dc-4423-bc3f-63142c9ad00d,108416.0,Short Term,725.0,1168272.0,10+ years,Rent,Debt Consolidation,41882.46,20.4,0.0,11.0,0.0,827051.0,1003816.0,0.0,0.0
27,ac8e5698-16a9-46f0-8b57-3fa2e145f8fd,9a561b03-ce0c-411e-85b4-73a108718cb7,108152.0,Short Term,705.0,747156.0,4 years,Rent,Business Loan,20235.38,19.9,15.0,14.0,0.0,174344.0,348062.0,0.0,0.0
28,a656f70b-632d-4513-a20b-88f1edf2c21e,3b69f3b7-4675-4bec-be5c-332d729b284c,174724.0,Short Term,725.0,1168272.0,5 years,Rent,Debt Consolidation,11341.29,8.2,0.0,4.0,0.0,85633.0,126632.0,0.0,0.0
29,6b3d25b3-33b8-41e3-9995-d6a274ac5844,3d5b68c4-e36c-4562-ac2e-1845c8a3f138,404008.0,Long Term,725.0,1168272.0,6 years,Home Mortgage,Debt Consolidation,42159.86,15.9,0.0,16.0,0.0,684950.0,1054636.0,0.0,0.0

In [ ]:
from google.colab import files

# Save the dataframe to a CSV file
df.to_csv('cleaned_credit_test.csv', index=False)

# This command triggers a browser download to your local computer
files.download('cleaned_credit_test.csv')